USE BD_CARDIP
GO			

DECLARE
		@P_FECHA_INICIO		DATETIME = N'2022/01/01',
		@P_FECHA_FIN		DATETIME = N'2022/06/30',
		@P_CALIDAD_MIG		SMALLINT = 0,
		@P_ESTADO			SMALLINT = 0,
		@P_OFCO_EX			SMALLINT = 0,
		@P_TIPO_BUSQUEDA	VARCHAR(20)= N'REGISTRO'
			
			SELECT		DISTINCT
						ISNULL(CARDIP.CAID_VCARNE_NUMERO,'[ S/N ]') AS NUMERO_CARNE,
						ESTADO.ESTA_VDESCRIPCIONCORTA AS ESTADO,
						ISNULL(CALMIG.CAMI_VNOMBRE,ISNULL(REGPREV_CALMIG.CAMI_VNOMBRE,'-')) AS CALIDAD_MIGRATORIA,
						ISNULL(CONVERT(VARCHAR,CARDIP.CAID_DFECHACREACION,103),'-') AS FECHA_INSCRIPCION,
						ISNULL(CONVERT(VARCHAR,CARDIP.CAID_DFECHA_EMISION,103),'-') AS FECHA_EMISION,
						ISNULL(CONVERT(VARCHAR,CARDIP.CAID_DFECHA_VENCIMIENTO,103),'-') AS FECHA_VENCIMIENTO,
						(
							CASE
								WHEN (PERSONA.PERS_VAPELLIDOPATERNO + ' ' + ISNULL(PERSONA.PERS_VAPELLIDOMATERNO,'') + ', ' + PERSONA.PERS_VNOMBRES) IS NULL
									THEN REGPREV.REPE_VPRIMER_APELLIDO + ' ' + ISNULL(REGPREV.REPE_VSEGUNDO_APELLIDO,'') + ' ' + REGPREV.REPE_VNOMBRES 
								ELSE (PERSONA.PERS_VAPELLIDOPATERNO + ' ' + ISNULL(PERSONA.PERS_VAPELLIDOMATERNO,'') + ', ' + PERSONA.PERS_VNOMBRES)
							END	
						) AS TITULAR,		
						ISNULL(TITDEP.PARA_VDESCRIPCION,'-') AS STATUS_MIG,				
						ISNULL((PAIS.PAIS_VNOMBRE + ' (' + ISNULL(PAIS.PAIS_VNACIONALIDAD,'[ NO DEFINIDO ]') + ')'),'-') AS PAIS_NACIONALIDAD,
						ISNULL(OFCOEX.OFCE_VNOMBRE,REGPREV_OFCO.OFCE_VNOMBRE) AS OFICINA_CONSULAR_EXTRANJERA,
						ISNULL(CALMIGSEC.CAMI_VNOMBRE,'-') AS CARGO,
						ISNULL(ESTCIVIL.PARA_VDESCRIPCION,'-') AS ECIVIL,
						ISNULL(PERSONA.PERS_VTELEFONO,'-') AS TELEFONO,
						ISNULL(PERSONA.PERS_VCORREOELECTRONICO,'-')CORREO_ELECTRONICO,
						ISNULL(UBIGEO.UBGE_VDEPARTAMENTO,'-') AS DEPARTAMENTO,
						ISNULL(UBIGEO.UBGE_VPROVINCIA,'-') AS PROVINCIA,
						ISNULL(UBIGEO.UBGE_VDISTRITO,'-') AS DISTRITO,
						ISNULL(RESIDENCIA.RESI_VRESIDENCIADIRECCION,'-') AS DIRECCION

			FROM			SC_CARDIP.CD_CARNE_IDENTIDAD CARDIP 
				LEFT JOIN	PN_REGISTRO.RE_PERSONA PERSONA ON CARDIP.CAID_IPERSONAID=PERSONA.PERS_IPERSONAID
				LEFT JOIN	PS_SISTEMA.SI_PARAMETRO SEXO ON PERSONA.PERS_SGENEROID = SEXO.PARA_SPARAMETROID
				LEFT JOIN	PS_SISTEMA.SI_PARAMETRO ESTCIVIL ON PERSONA.PERS_SESTADOCIVILID = ESTCIVIL.PARA_SPARAMETROID
				LEFT JOIN	SC_MAESTRO.MA_CALIDAD_MIGRATORIA CALMIG ON CARDIP.CAID_SCALIDAD_MIGRATORIAID = CALMIG.CAMI_SCALIDAD_MIGRATORIAID
				LEFT JOIN	SC_MAESTRO.MA_CALIDAD_MIGRATORIA CALMIGSEC ON CARDIP.CAID_SCALIDAD_MIGRATORIA_SEC_ID = CALMIGSEC.CAMI_SCALIDAD_MIGRATORIAID
				LEFT JOIN	PS_SISTEMA.SI_PARAMETRO TITDEP ON CALMIGSEC.CAMI_SFLAG_TITULAR_DEPENDIENTE = TITDEP.PARA_SPARAMETROID
				LEFT JOIN	PS_SISTEMA.SI_OFICINACONSULAR_EXTRANJERA OFCOEX ON CARDIP.CAID_SOFICINA_CONSULAR_EXID = OFCOEX.OFCE_SOFICINACONSULAR_EXTRANJERAID
				LEFT JOIN	PS_SISTEMA.SI_PARAMETRO CATMISION ON OFCOEX.OFCE_SCATEGORIAID = CATMISION.PARA_SPARAMETROID
				LEFT JOIN	SC_MAESTRO.MA_ESTADO ESTADO ON CARDIP.CAID_SESTADOID = ESTADO.ESTA_SESTADOID
				LEFT JOIN	PS_SISTEMA.SI_PAIS PAIS ON PERSONA.PERS_SPAISID = PAIS.PAIS_SPAISID
				LEFT JOIN	SC_CARDIP.CD_REGISTRO_PREVIO REGPREV ON CARDIP.CAID_SREGISTRO_PREVIO = REGPREV.REPE_SREGISTRO_PREVIO_ID
				LEFT JOIN	SC_MAESTRO.MA_CALIDAD_MIGRATORIA REGPREV_CALMIG ON REGPREV.REPE_SCALIDAD_MIGRATORIA = REGPREV_CALMIG.CAMI_SCALIDAD_MIGRATORIAID
				LEFT JOIN	PS_SISTEMA.SI_OFICINACONSULAR_EXTRANJERA REGPREV_OFCO ON REGPREV.REPE_SOFICINA_CONSULAR_EX_ID = REGPREV_OFCO.OFCE_SOFICINACONSULAR_EXTRANJERAID
				LEFT JOIN	PS_SISTEMA.SI_PARAMETRO REGPREV_OFCO_CAT ON REGPREV_OFCO.OFCE_SCATEGORIAID = REGPREV_OFCO_CAT.PARA_SPARAMETROID
				LEFT JOIN	PS_SISTEMA.SI_PARAMETRO REGPREV_GENERO ON REGPREV.REPE_SGENERO_ID = REGPREV_GENERO.PARA_SPARAMETROID

				LEFT JOIN	PN_REGISTRO.RE_PERSONARESIDENCIA PERSRESID ON PERSRESID.PERE_IPERSONAID = PERSONA.PERS_IPERSONAID
				LEFT JOIN	PN_REGISTRO.RE_RESIDENCIA RESIDENCIA ON RESIDENCIA.RESI_IRESIDENCIAID = PERSRESID.PERE_IRESIDENCIAID
				LEFT JOIN	PS_SISTEMA.SI_UBICACIONGEOGRAFICA UBIGEO ON UBIGEO.UBGE_CCODIGO = RESIDENCIA.RESI_CRESIDENCIAUBIGEO
							AND UBIGEO.UBGE_CESTADO = 'A' 

			WHERE		CAST(FLOOR(CAST(CAID_DFECHACREACION AS float)) AS DATETIME)>=@P_FECHA_INICIO
			AND			CAST(FLOOR(CAST(CAID_DFECHACREACION AS float)) AS DATETIME)<=@P_FECHA_FIN
			AND			(@P_CALIDAD_MIG=0 OR CARDIP.CAID_SCALIDAD_MIGRATORIAID=@P_CALIDAD_MIG)
			AND			(@P_ESTADO=0 OR CARDIP.CAID_SESTADOID=@P_ESTADO)
			AND			(@P_OFCO_EX=0 OR CARDIP.CAID_SOFICINA_CONSULAR_EXID=@P_OFCO_EX)



--SELECT * FROM SC_CARDIP.CD_CARNE_IDENTIDAD CARDIP 
--WHERE CAID_VCARNE_NUMERO = 20220006

--SELECT * FROM PN_REGISTRO.RE_PERSONA PERSONA
--WHERE PERS_IPERSONAID = 10090

--SELECT  
--UBIGEO.UBGE_VDEPARTAMENTO,
--UBIGEO.UBGE_VPROVINCIA,
--UBIGEO.UBGE_VDISTRITO,
--RESIDENCIA.RESI_VRESIDENCIADIRECCION
--FROM PN_REGISTRO.RE_PERSONA PERSONA
--LEFT JOIN PN_REGISTRO.RE_PERSONARESIDENCIA PERSRESID ON PERSRESID.PERE_IPERSONAID = PERSONA.PERS_IPERSONAID
--LEFT JOIN PN_REGISTRO.RE_RESIDENCIA RESIDENCIA ON RESIDENCIA.RESI_IRESIDENCIAID = PERSRESID.PERE_IRESIDENCIAID
--LEFT JOIN PS_SISTEMA.SI_PAIS PAIS ON PERSONA.PERS_SPAISID = PAIS.PAIS_SPAISID
--LEFT JOIN PS_SISTEMA.SI_UBICACIONGEOGRAFICA UBIGEO ON UBIGEO.UBGE_CCODIGO = RESIDENCIA.RESI_CRESIDENCIAUBIGEO
--AND UBIGEO.UBGE_CESTADO = 'A' 
--WHERE PERE_IPERSONAID = 10090

--SELECT * FROM PN_REGISTRO.RE_RESIDENCIA
--WHERE RESI_IRESIDENCIAID=10166

--SELECT * FROM PS_SISTEMA.SI_UBICACIONGEOGRAFICA
--WHERE  UBGE_VSIGLAPAIS = 'ARG'
----UBGE_CCODIGO = 180302

--SELECT * FROM PS_SISTEMA.SI_PAIS PAIS 
--WHERE PAIS_SPAISID = 13



--SELECT * FROM PS_SISTEMA.SI_PARAMETRO SEXO 
--SELECT * FROM PS_SISTEMA.SI_PARAMETRO ESTCIVIL 
--SELECT * FROM SC_MAESTRO.MA_CALIDAD_MIGRATORIA CALMIG 
--SELECT * FROM SC_MAESTRO.MA_CALIDAD_MIGRATORIA CALMIGSEC 
--SELECT * FROM PS_SISTEMA.SI_PARAMETRO TITDEP 
--SELECT * FROM PS_SISTEMA.SI_OFICINACONSULAR_EXTRANJERA OFCOEX 
--SELECT * FROM PS_SISTEMA.SI_PARAMETRO CATMISION 
--SELECT * FROM SC_MAESTRO.MA_ESTADO ESTADO 
--SELECT * FROM PS_SISTEMA.SI_PAIS PAIS 
--SELECT * FROM SC_CARDIP.CD_REGISTRO_PREVIO REGPREV 
--SELECT * FROM SC_MAESTRO.MA_CALIDAD_MIGRATORIA REGPREV_CALMIG 
--SELECT * FROM PS_SISTEMA.SI_OFICINACONSULAR_EXTRANJERA REGPREV_OFCO 
--SELECT * FROM PS_SISTEMA.SI_PARAMETRO REGPREV_OFCO_CAT 
--SELECT * FROM PS_SISTEMA.SI_PARAMETRO REGPREV_GENERO 


















































