
USE BD_CARDIP

SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_CARNE_IDENTIDAD' AND C.COLUMN_NAME = 'CAID_ICARNE_IDENTIDADID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_CARNE_IDENTIDAD_RELACION_DEPENDENCIA' AND C.COLUMN_NAME = 'CATD_SCARNE_IDENTIDAD_DEP_ID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_CARNE_IDENTIDAD_RELACION_DEPENDENCIA' AND C.COLUMN_NAME = 'CATD_SCARNE_IDENTIDAD_TIT_ID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_ACTA_RECEPCION_DETALLE' AND C.COLUMN_NAME = 'ACRD_SCARNE_IDENTIDAD_ID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_MOVIMIENTO_CARNE_IDENTIDAD' AND C.COLUMN_NAME = 'MOCI_ICARNE_IDENTIDADID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_CARNE_IDENTIDAD_HISTORICO' AND C.COLUMN_NAME = 'CIHI_ICARNE_IDENTIDADID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_ACTA_CONFORMIDAD_DETALLE' AND C.COLUMN_NAME = 'ACDE_SCARNE_IDENTIDAD_ID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_REGLINEA' AND C.TABLE_NAME = 'RL_REGISTRO_LINEA' AND C.COLUMN_NAME = 'RELI_SDP_RELDEP_TITULAR'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_REGLINEA' AND C.TABLE_NAME = 'RL_REGISTRO_LINEA' AND C.COLUMN_NAME = 'RELI_ICARNE_IDENTIDAD_ID'
UNION ALL
SELECT C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS AS C 
WHERE C.TABLE_SCHEMA = 'SC_CARDIP' AND C.TABLE_NAME = 'CD_CARNE_IDENTIDAD_SOLICITUD' AND C.COLUMN_NAME = 'CAIS_SCARNE_IDENTIDAD_ID'













