//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SGAC.BE
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RE_EMPRESA))]
    [KnownType(typeof(SE_USUARIO))]
    [KnownType(typeof(RE_PERSONA))]
    public partial class RE_REPRESENTANTELEGAL: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int rele_iRepresentanteLegalId
        {
            get { return _rele_iRepresentanteLegalId; }
            set
            {
                if (_rele_iRepresentanteLegalId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'rele_iRepresentanteLegalId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _rele_iRepresentanteLegalId = value;
                    OnPropertyChanged("rele_iRepresentanteLegalId");
                }
            }
        }
        private int _rele_iRepresentanteLegalId;
    
        [DataMember]
        public long rele_iEmpresaId
        {
            get { return _rele_iEmpresaId; }
            set
            {
                if (_rele_iEmpresaId != value)
                {
                    ChangeTracker.RecordOriginalValue("rele_iEmpresaId", _rele_iEmpresaId);
                    if (!IsDeserializing)
                    {
                        if (RE_EMPRESA != null && RE_EMPRESA.empr_iEmpresaId != value)
                        {
                            RE_EMPRESA = null;
                        }
                    }
                    _rele_iEmpresaId = value;
                    OnPropertyChanged("rele_iEmpresaId");
                }
            }
        }
        private long _rele_iEmpresaId;
    
        [DataMember]
        public Nullable<long> rele_iPersonaId
        {
            get { return _rele_iPersonaId; }
            set
            {
                if (_rele_iPersonaId != value)
                {
                    ChangeTracker.RecordOriginalValue("rele_iPersonaId", _rele_iPersonaId);
                    if (!IsDeserializing)
                    {
                        if (RE_PERSONA != null && RE_PERSONA.pers_iPersonaId != value)
                        {
                            RE_PERSONA = null;
                        }
                    }
                    _rele_iPersonaId = value;
                    OnPropertyChanged("rele_iPersonaId");
                }
            }
        }
        private Nullable<long> _rele_iPersonaId;
    
        [DataMember]
        public Nullable<System.DateTime> rele_dFechaInicio
        {
            get { return _rele_dFechaInicio; }
            set
            {
                if (_rele_dFechaInicio != value)
                {
                    _rele_dFechaInicio = value;
                    OnPropertyChanged("rele_dFechaInicio");
                }
            }
        }
        private Nullable<System.DateTime> _rele_dFechaInicio;
    
        [DataMember]
        public Nullable<System.DateTime> rele_dFechaFin
        {
            get { return _rele_dFechaFin; }
            set
            {
                if (_rele_dFechaFin != value)
                {
                    _rele_dFechaFin = value;
                    OnPropertyChanged("rele_dFechaFin");
                }
            }
        }
        private Nullable<System.DateTime> _rele_dFechaFin;
    
        [DataMember]
        public string rele_cEstado
        {
            get { return _rele_cEstado; }
            set
            {
                if (_rele_cEstado != value)
                {
                    _rele_cEstado = value;
                    OnPropertyChanged("rele_cEstado");
                }
            }
        }
        private string _rele_cEstado;
    
        [DataMember]
        public short rele_sUsuarioCreacion
        {
            get { return _rele_sUsuarioCreacion; }
            set
            {
                if (_rele_sUsuarioCreacion != value)
                {
                    ChangeTracker.RecordOriginalValue("rele_sUsuarioCreacion", _rele_sUsuarioCreacion);
                    if (!IsDeserializing)
                    {
                        if (SE_USUARIO != null && SE_USUARIO.usua_sUsuarioId != value)
                        {
                            SE_USUARIO = null;
                        }
                    }
                    _rele_sUsuarioCreacion = value;
                    OnPropertyChanged("rele_sUsuarioCreacion");
                }
            }
        }
        private short _rele_sUsuarioCreacion;
    
        [DataMember]
        public string rele_vIPCreacion
        {
            get { return _rele_vIPCreacion; }
            set
            {
                if (_rele_vIPCreacion != value)
                {
                    _rele_vIPCreacion = value;
                    OnPropertyChanged("rele_vIPCreacion");
                }
            }
        }
        private string _rele_vIPCreacion;
    
        [DataMember]
        public System.DateTime rele_dFechaCreacion
        {
            get { return _rele_dFechaCreacion; }
            set
            {
                if (_rele_dFechaCreacion != value)
                {
                    _rele_dFechaCreacion = value;
                    OnPropertyChanged("rele_dFechaCreacion");
                }
            }
        }
        private System.DateTime _rele_dFechaCreacion;
    
        [DataMember]
        public Nullable<short> rele_sUsuarioModificacion
        {
            get { return _rele_sUsuarioModificacion; }
            set
            {
                if (_rele_sUsuarioModificacion != value)
                {
                    ChangeTracker.RecordOriginalValue("rele_sUsuarioModificacion", _rele_sUsuarioModificacion);
                    if (!IsDeserializing)
                    {
                        if (SE_USUARIO1 != null && SE_USUARIO1.usua_sUsuarioId != value)
                        {
                            SE_USUARIO1 = null;
                        }
                    }
                    _rele_sUsuarioModificacion = value;
                    OnPropertyChanged("rele_sUsuarioModificacion");
                }
            }
        }
        private Nullable<short> _rele_sUsuarioModificacion;
    
        [DataMember]
        public string rele_vIPModificacion
        {
            get { return _rele_vIPModificacion; }
            set
            {
                if (_rele_vIPModificacion != value)
                {
                    _rele_vIPModificacion = value;
                    OnPropertyChanged("rele_vIPModificacion");
                }
            }
        }
        private string _rele_vIPModificacion;
    
        [DataMember]
        public Nullable<System.DateTime> rele_dFechaModificacion
        {
            get { return _rele_dFechaModificacion; }
            set
            {
                if (_rele_dFechaModificacion != value)
                {
                    _rele_dFechaModificacion = value;
                    OnPropertyChanged("rele_dFechaModificacion");
                }
            }
        }
        private Nullable<System.DateTime> _rele_dFechaModificacion;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public RE_EMPRESA RE_EMPRESA
        {
            get { return _rE_EMPRESA; }
            set
            {
                if (!ReferenceEquals(_rE_EMPRESA, value))
                {
                    var previousValue = _rE_EMPRESA;
                    _rE_EMPRESA = value;
                    FixupRE_EMPRESA(previousValue);
                    OnNavigationPropertyChanged("RE_EMPRESA");
                }
            }
        }
        private RE_EMPRESA _rE_EMPRESA;
    
        [DataMember]
        public SE_USUARIO SE_USUARIO
        {
            get { return _sE_USUARIO; }
            set
            {
                if (!ReferenceEquals(_sE_USUARIO, value))
                {
                    var previousValue = _sE_USUARIO;
                    _sE_USUARIO = value;
                    FixupSE_USUARIO(previousValue);
                    OnNavigationPropertyChanged("SE_USUARIO");
                }
            }
        }
        private SE_USUARIO _sE_USUARIO;
    
        [DataMember]
        public SE_USUARIO SE_USUARIO1
        {
            get { return _sE_USUARIO1; }
            set
            {
                if (!ReferenceEquals(_sE_USUARIO1, value))
                {
                    var previousValue = _sE_USUARIO1;
                    _sE_USUARIO1 = value;
                    FixupSE_USUARIO1(previousValue);
                    OnNavigationPropertyChanged("SE_USUARIO1");
                }
            }
        }
        private SE_USUARIO _sE_USUARIO1;
    
        [DataMember]
        public RE_PERSONA RE_PERSONA
        {
            get { return _rE_PERSONA; }
            set
            {
                if (!ReferenceEquals(_rE_PERSONA, value))
                {
                    var previousValue = _rE_PERSONA;
                    _rE_PERSONA = value;
                    FixupRE_PERSONA(previousValue);
                    OnNavigationPropertyChanged("RE_PERSONA");
                }
            }
        }
        private RE_PERSONA _rE_PERSONA;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
    
    
    
    		private Int16 _sOficinaConsularId;
    	[DataMember]
        public Int16 OficinaConsularId
        {
            get
            {
    			return _sOficinaConsularId;
    		}
    		set
    		{
    			_sOficinaConsularId = value;
    		}
    	}
    	private Int16 _sDiferenciaHoraria;
    	[DataMember]
        public Int16 DiferenciaHoraria
        {
            get
            {
    			return _sDiferenciaHoraria;
    		}
    		set
    		{
    			_sDiferenciaHoraria = value;
    		}
    	}
    	private Int16 _sHorarioVerano;
    	[DataMember]
        public Int16 HorarioVerano
        {
            get
            {
    			return _sHorarioVerano;
    		}
    		set
    		{
    			_sHorarioVerano = value;
    		}
    	}
    
    
    
    
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            RE_EMPRESA = null;
            SE_USUARIO = null;
            SE_USUARIO1 = null;
            RE_PERSONA = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupRE_EMPRESA(RE_EMPRESA previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_REPRESENTANTELEGAL.Contains(this))
            {
                previousValue.RE_REPRESENTANTELEGAL.Remove(this);
            }
    
            if (RE_EMPRESA != null)
            {
                if (!RE_EMPRESA.RE_REPRESENTANTELEGAL.Contains(this))
                {
                    RE_EMPRESA.RE_REPRESENTANTELEGAL.Add(this);
                }
    
                rele_iEmpresaId = RE_EMPRESA.empr_iEmpresaId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RE_EMPRESA")
                    && (ChangeTracker.OriginalValues["RE_EMPRESA"] == RE_EMPRESA))
                {
                    ChangeTracker.OriginalValues.Remove("RE_EMPRESA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RE_EMPRESA", previousValue);
                }
                if (RE_EMPRESA != null && !RE_EMPRESA.ChangeTracker.ChangeTrackingEnabled)
                {
                    RE_EMPRESA.StartTracking();
                }
            }
        }
    
        private void FixupSE_USUARIO(SE_USUARIO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_REPRESENTANTELEGAL.Contains(this))
            {
                previousValue.RE_REPRESENTANTELEGAL.Remove(this);
            }
    
            if (SE_USUARIO != null)
            {
                if (!SE_USUARIO.RE_REPRESENTANTELEGAL.Contains(this))
                {
                    SE_USUARIO.RE_REPRESENTANTELEGAL.Add(this);
                }
    
                rele_sUsuarioCreacion = SE_USUARIO.usua_sUsuarioId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SE_USUARIO")
                    && (ChangeTracker.OriginalValues["SE_USUARIO"] == SE_USUARIO))
                {
                    ChangeTracker.OriginalValues.Remove("SE_USUARIO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SE_USUARIO", previousValue);
                }
                if (SE_USUARIO != null && !SE_USUARIO.ChangeTracker.ChangeTrackingEnabled)
                {
                    SE_USUARIO.StartTracking();
                }
            }
        }
    
        private void FixupSE_USUARIO1(SE_USUARIO previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_REPRESENTANTELEGAL1.Contains(this))
            {
                previousValue.RE_REPRESENTANTELEGAL1.Remove(this);
            }
    
            if (SE_USUARIO1 != null)
            {
                if (!SE_USUARIO1.RE_REPRESENTANTELEGAL1.Contains(this))
                {
                    SE_USUARIO1.RE_REPRESENTANTELEGAL1.Add(this);
                }
    
                rele_sUsuarioModificacion = SE_USUARIO1.usua_sUsuarioId;
            }
            else if (!skipKeys)
            {
                rele_sUsuarioModificacion = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SE_USUARIO1")
                    && (ChangeTracker.OriginalValues["SE_USUARIO1"] == SE_USUARIO1))
                {
                    ChangeTracker.OriginalValues.Remove("SE_USUARIO1");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SE_USUARIO1", previousValue);
                }
                if (SE_USUARIO1 != null && !SE_USUARIO1.ChangeTracker.ChangeTrackingEnabled)
                {
                    SE_USUARIO1.StartTracking();
                }
            }
        }
    
        private void FixupRE_PERSONA(RE_PERSONA previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_REPRESENTANTELEGAL.Contains(this))
            {
                previousValue.RE_REPRESENTANTELEGAL.Remove(this);
            }
    
            if (RE_PERSONA != null)
            {
                if (!RE_PERSONA.RE_REPRESENTANTELEGAL.Contains(this))
                {
                    RE_PERSONA.RE_REPRESENTANTELEGAL.Add(this);
                }
    
                rele_iPersonaId = RE_PERSONA.pers_iPersonaId;
            }
            else if (!skipKeys)
            {
                rele_iPersonaId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RE_PERSONA")
                    && (ChangeTracker.OriginalValues["RE_PERSONA"] == RE_PERSONA))
                {
                    ChangeTracker.OriginalValues.Remove("RE_PERSONA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RE_PERSONA", previousValue);
                }
                if (RE_PERSONA != null && !RE_PERSONA.ChangeTracker.ChangeTrackingEnabled)
                {
                    RE_PERSONA.StartTracking();
                }
            }
        }

        #endregion
    }
}
