USE [BD_CARDIP]
GO

ALTER TABLE [SC_CARDIP].[CD_CARNE_IDENTIDAD_RELACION_DEPENDENCIA]  WITH CHECK ADD  CONSTRAINT [FK_CARNE_IDENTIDAD_TIT_DEP_CARNE_IDENTIDAD_TIT] FOREIGN KEY([CATD_SCARNE_IDENTIDAD_TIT_ID])
REFERENCES [SC_CARDIP].[CD_CARNE_IDENTIDAD] ([CAID_ICARNE_IDENTIDADID])
GO

ALTER TABLE [SC_CARDIP].[CD_CARNE_IDENTIDAD_RELACION_DEPENDENCIA] CHECK CONSTRAINT [FK_CARNE_IDENTIDAD_TIT_DEP_CARNE_IDENTIDAD_TIT]
GO
