USE [BD_CARDIP]
GO

IF NOT EXISTS (SELECT object_id FROM sys.objects WHERE object_id = OBJECT_ID(N'[SC_CARDIP].[USP_CD_MANTENER_MENSAJE_ESTADO]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [SC_CARDIP].[USP_CD_MANTENER_MENSAJE_ESTADO] AS' 
END
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER  PROCEDURE [SC_CARDIP].[USP_CD_MANTENER_MENSAJE_ESTADO]
--======================================================================
--SISTEMA		:	
--OBJETIVO		: VPIPA	
--CREADO POR		:	
--FECHA			:	07/10/2019
--PARAMETROS		:	@MEES_SESTADOID,@MEES_VMENSAJE
--EJECUTAR		:	[SC_CARDIP].[USP_CD_MANTENER_MENSAJE_ESTADO] 1,'asdasdasdad'
--MODIFICACIONES
--AUTOR		FECHA		N° REQ		MOTIVO		
--======================================================================
@MEES_SESTADOID SMALLINT,
@MEES_VMENSAJE  VARCHAR(250),
@OPERACION		VARCHAR(10)
AS
BEGIN
	BEGIN TRY
		IF (@OPERACION='INSERT') 
		BEGIN

		--NO SE PUEDE INSERTAR DUPLICADO CUAND EL ANTERIOR  ETA´ANULADO
			INSERT INTO SC_CARDIP.CD_MENSAJE_ESTADO (MEES_SESTADOID,MEES_VMENSAJE,MEES_CESTADO)
				VALUES(@MEES_SESTADOID,@MEES_VMENSAJE,'A')
		END 
		ELSE IF(@OPERACION='UPDATE') 
		BEGIN
			UPDATE  SC_CARDIP.CD_MENSAJE_ESTADO  SET  MEES_VMENSAJE=@MEES_VMENSAJE 	
				WHERE MEES_SESTADOID=@MEES_SESTADOID
		END ELSE IF(@OPERACION='DELETE') 
		BEGIN
			UPDATE  SC_CARDIP.CD_MENSAJE_ESTADO  SET  MEES_CESTADO='I' 	
				WHERE MEES_SESTADOID=@MEES_SESTADOID
		END			
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
	END CATCH
END

