USE [BD_CARDIP]
GO

GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_CARNE_IDENTIDAD_ACTUALIZAR_ESTADO_OBSERVADO] TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_CONSULTA_REGLINEA_XIDCARNET]TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_REGITROLINEA_REGISTRAR_DETALLE] TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_CARNE_IDENTIDAD_OBTENER_CORREO] TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_CONSULTA_MENSAJE_ESTADO] TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_REPORTE_CONSULTA_CARNET]TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_MANTENER_MENSAJE_ESTADO]TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_REGITROLINEA_REGISTRAR_DETALLE_ATENDIDO]TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_CONSULTA_MENSAJE_ESTADO]TO AU_CARDIP,AU_REGLINEA
GRANT EXECUTE ON OBJECT::[SC_CARDIP].[USP_CD_REGITROLINEA_REGISTRAR_DETALLE_APROBADO]TO AU_CARDIP,AU_REGLINEA
go




