USE BD_CARDIP

DECLARE @COLUM VARCHAR(MAX)='MOCI_ICARNE_IDENTIDADID'
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS AS C
	WHERE C.TABLE_SCHEMA = 'SC_CARDIP'
	AND C.TABLE_NAME = 'CD_MOVIMIENTO_CARNE_IDENTIDAD'
    AND C.COLUMN_NAME = @COLUM
	)
BEGIN
	ALTER TABLE [SC_CARDIP].[CD_MOVIMIENTO_CARNE_IDENTIDAD]
		ALTER COLUMN [MOCI_ICARNE_IDENTIDADID] INT;
	
	PRINT 'CAMPO '+@COLUM+' ¡¡AFECTADA!!'
END

GO



