USE [BD_CARDIP]
GO

ALTER TABLE [SC_CARDIP].[CD_ACTA_RECEPCION_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_ACTA_RECEPCION_DETALLE_CARNE_IDENTIDAD] FOREIGN KEY([ACRD_SCARNE_IDENTIDAD_ID])
REFERENCES [SC_CARDIP].[CD_CARNE_IDENTIDAD] ([CAID_ICARNE_IDENTIDADID])
GO

ALTER TABLE [SC_CARDIP].[CD_ACTA_RECEPCION_DETALLE] CHECK CONSTRAINT [FK_ACTA_RECEPCION_DETALLE_CARNE_IDENTIDAD]
GO