//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SGAC.BE
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RE_EMPRESA))]
    [KnownType(typeof(SE_USUARIO))]
    [KnownType(typeof(RE_PERSONA))]
    [KnownType(typeof(SI_PARAMETRO))]
    [KnownType(typeof(RE_ACTONOTARIAL))]
    public partial class RE_ACTONOTARIALPARTICIPANTE: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long anpa_iActoNotarialParticipanteId
        {
            get { return _anpa_iActoNotarialParticipanteId; }
            set
            {
                if (_anpa_iActoNotarialParticipanteId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'anpa_iActoNotarialParticipanteId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _anpa_iActoNotarialParticipanteId = value;
                    OnPropertyChanged("anpa_iActoNotarialParticipanteId");
                }
            }
        }
        private long _anpa_iActoNotarialParticipanteId;
    
        [DataMember]
        public long anpa_iActoNotarialId
        {
            get { return _anpa_iActoNotarialId; }
            set
            {
                if (_anpa_iActoNotarialId != value)
                {
                    ChangeTracker.RecordOriginalValue("anpa_iActoNotarialId", _anpa_iActoNotarialId);
                    if (!IsDeserializing)
                    {
                        if (RE_ACTONOTARIAL != null && RE_ACTONOTARIAL.acno_iActoNotarialId != value)
                        {
                            RE_ACTONOTARIAL = null;
                        }
                    }
                    _anpa_iActoNotarialId = value;
                    OnPropertyChanged("anpa_iActoNotarialId");
                }
            }
        }
        private long _anpa_iActoNotarialId;
    
        [DataMember]
        public Nullable<long> anpa_iPersonaId
        {
            get { return _anpa_iPersonaId; }
            set
            {
                if (_anpa_iPersonaId != value)
                {
                    ChangeTracker.RecordOriginalValue("anpa_iPersonaId", _anpa_iPersonaId);
                    if (!IsDeserializing)
                    {
                        if (RE_PERSONA != null && RE_PERSONA.pers_iPersonaId != value)
                        {
                            RE_PERSONA = null;
                        }
                    }
                    _anpa_iPersonaId = value;
                    OnPropertyChanged("anpa_iPersonaId");
                }
            }
        }
        private Nullable<long> _anpa_iPersonaId;
    
        [DataMember]
        public Nullable<long> anpa_iEmpresaId
        {
            get { return _anpa_iEmpresaId; }
            set
            {
                if (_anpa_iEmpresaId != value)
                {
                    ChangeTracker.RecordOriginalValue("anpa_iEmpresaId", _anpa_iEmpresaId);
                    if (!IsDeserializing)
                    {
                        if (RE_EMPRESA != null && RE_EMPRESA.empr_iEmpresaId != value)
                        {
                            RE_EMPRESA = null;
                        }
                    }
                    _anpa_iEmpresaId = value;
                    OnPropertyChanged("anpa_iEmpresaId");
                }
            }
        }
        private Nullable<long> _anpa_iEmpresaId;
    
        [DataMember]
        public short anpa_sTipoParticipanteId
        {
            get { return _anpa_sTipoParticipanteId; }
            set
            {
                if (_anpa_sTipoParticipanteId != value)
                {
                    ChangeTracker.RecordOriginalValue("anpa_sTipoParticipanteId", _anpa_sTipoParticipanteId);
                    if (!IsDeserializing)
                    {
                        if (SE_USUARIO2 != null && SE_USUARIO2.usua_sUsuarioId != value)
                        {
                            SE_USUARIO2 = null;
                        }
                        if (SI_PARAMETRO != null && SI_PARAMETRO.para_sParametroId != value)
                        {
                            SI_PARAMETRO = null;
                        }
                    }
                    _anpa_sTipoParticipanteId = value;
                    OnPropertyChanged("anpa_sTipoParticipanteId");
                }
            }
        }
        private short _anpa_sTipoParticipanteId;
    
        [DataMember]
        public Nullable<bool> anpa_bFlagFirma
        {
            get { return _anpa_bFlagFirma; }
            set
            {
                if (_anpa_bFlagFirma != value)
                {
                    _anpa_bFlagFirma = value;
                    OnPropertyChanged("anpa_bFlagFirma");
                }
            }
        }
        private Nullable<bool> _anpa_bFlagFirma;
    
        [DataMember]
        public Nullable<bool> anpa_bFlagHuella
        {
            get { return _anpa_bFlagHuella; }
            set
            {
                if (_anpa_bFlagHuella != value)
                {
                    _anpa_bFlagHuella = value;
                    OnPropertyChanged("anpa_bFlagHuella");
                }
            }
        }
        private Nullable<bool> _anpa_bFlagHuella;
    
        [DataMember]
        public string anpa_cEstado
        {
            get { return _anpa_cEstado; }
            set
            {
                if (_anpa_cEstado != value)
                {
                    _anpa_cEstado = value;
                    OnPropertyChanged("anpa_cEstado");
                }
            }
        }
        private string _anpa_cEstado;
    
        [DataMember]
        public short anpa_sUsuarioCreacion
        {
            get { return _anpa_sUsuarioCreacion; }
            set
            {
                if (_anpa_sUsuarioCreacion != value)
                {
                    ChangeTracker.RecordOriginalValue("anpa_sUsuarioCreacion", _anpa_sUsuarioCreacion);
                    if (!IsDeserializing)
                    {
                        if (SE_USUARIO != null && SE_USUARIO.usua_sUsuarioId != value)
                        {
                            SE_USUARIO = null;
                        }
                    }
                    _anpa_sUsuarioCreacion = value;
                    OnPropertyChanged("anpa_sUsuarioCreacion");
                }
            }
        }
        private short _anpa_sUsuarioCreacion;
    
        [DataMember]
        public string anpa_vIPCreacion
        {
            get { return _anpa_vIPCreacion; }
            set
            {
                if (_anpa_vIPCreacion != value)
                {
                    _anpa_vIPCreacion = value;
                    OnPropertyChanged("anpa_vIPCreacion");
                }
            }
        }
        private string _anpa_vIPCreacion;
    
        [DataMember]
        public System.DateTime anpa_dFechaCreacion
        {
            get { return _anpa_dFechaCreacion; }
            set
            {
                if (_anpa_dFechaCreacion != value)
                {
                    _anpa_dFechaCreacion = value;
                    OnPropertyChanged("anpa_dFechaCreacion");
                }
            }
        }
        private System.DateTime _anpa_dFechaCreacion;
    
        [DataMember]
        public Nullable<short> anpa_sUsuarioModificacion
        {
            get { return _anpa_sUsuarioModificacion; }
            set
            {
                if (_anpa_sUsuarioModificacion != value)
                {
                    ChangeTracker.RecordOriginalValue("anpa_sUsuarioModificacion", _anpa_sUsuarioModificacion);
                    if (!IsDeserializing)
                    {
                        if (SE_USUARIO1 != null && SE_USUARIO1.usua_sUsuarioId != value)
                        {
                            SE_USUARIO1 = null;
                        }
                    }
                    _anpa_sUsuarioModificacion = value;
                    OnPropertyChanged("anpa_sUsuarioModificacion");
                }
            }
        }
        private Nullable<short> _anpa_sUsuarioModificacion;
    
        [DataMember]
        public string anpa_vIPModificacion
        {
            get { return _anpa_vIPModificacion; }
            set
            {
                if (_anpa_vIPModificacion != value)
                {
                    _anpa_vIPModificacion = value;
                    OnPropertyChanged("anpa_vIPModificacion");
                }
            }
        }
        private string _anpa_vIPModificacion;
    
        [DataMember]
        public Nullable<System.DateTime> anpa_dFechaModificacion
        {
            get { return _anpa_dFechaModificacion; }
            set
            {
                if (_anpa_dFechaModificacion != value)
                {
                    _anpa_dFechaModificacion = value;
                    OnPropertyChanged("anpa_dFechaModificacion");
                }
            }
        }
        private Nullable<System.DateTime> _anpa_dFechaModificacion;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public RE_EMPRESA RE_EMPRESA
        {
            get { return _rE_EMPRESA; }
            set
            {
                if (!ReferenceEquals(_rE_EMPRESA, value))
                {
                    var previousValue = _rE_EMPRESA;
                    _rE_EMPRESA = value;
                    FixupRE_EMPRESA(previousValue);
                    OnNavigationPropertyChanged("RE_EMPRESA");
                }
            }
        }
        private RE_EMPRESA _rE_EMPRESA;
    
        [DataMember]
        public SE_USUARIO SE_USUARIO
        {
            get { return _sE_USUARIO; }
            set
            {
                if (!ReferenceEquals(_sE_USUARIO, value))
                {
                    var previousValue = _sE_USUARIO;
                    _sE_USUARIO = value;
                    FixupSE_USUARIO(previousValue);
                    OnNavigationPropertyChanged("SE_USUARIO");
                }
            }
        }
        private SE_USUARIO _sE_USUARIO;
    
        [DataMember]
        public SE_USUARIO SE_USUARIO1
        {
            get { return _sE_USUARIO1; }
            set
            {
                if (!ReferenceEquals(_sE_USUARIO1, value))
                {
                    var previousValue = _sE_USUARIO1;
                    _sE_USUARIO1 = value;
                    FixupSE_USUARIO1(previousValue);
                    OnNavigationPropertyChanged("SE_USUARIO1");
                }
            }
        }
        private SE_USUARIO _sE_USUARIO1;
    
        [DataMember]
        public SE_USUARIO SE_USUARIO2
        {
            get { return _sE_USUARIO2; }
            set
            {
                if (!ReferenceEquals(_sE_USUARIO2, value))
                {
                    var previousValue = _sE_USUARIO2;
                    _sE_USUARIO2 = value;
                    FixupSE_USUARIO2(previousValue);
                    OnNavigationPropertyChanged("SE_USUARIO2");
                }
            }
        }
        private SE_USUARIO _sE_USUARIO2;
    
        [DataMember]
        public RE_PERSONA RE_PERSONA
        {
            get { return _rE_PERSONA; }
            set
            {
                if (!ReferenceEquals(_rE_PERSONA, value))
                {
                    var previousValue = _rE_PERSONA;
                    _rE_PERSONA = value;
                    FixupRE_PERSONA(previousValue);
                    OnNavigationPropertyChanged("RE_PERSONA");
                }
            }
        }
        private RE_PERSONA _rE_PERSONA;
    
        [DataMember]
        public SI_PARAMETRO SI_PARAMETRO
        {
            get { return _sI_PARAMETRO; }
            set
            {
                if (!ReferenceEquals(_sI_PARAMETRO, value))
                {
                    var previousValue = _sI_PARAMETRO;
                    _sI_PARAMETRO = value;
                    FixupSI_PARAMETRO(previousValue);
                    OnNavigationPropertyChanged("SI_PARAMETRO");
                }
            }
        }
        private SI_PARAMETRO _sI_PARAMETRO;
    
        [DataMember]
        public RE_ACTONOTARIAL RE_ACTONOTARIAL
        {
            get { return _rE_ACTONOTARIAL; }
            set
            {
                if (!ReferenceEquals(_rE_ACTONOTARIAL, value))
                {
                    var previousValue = _rE_ACTONOTARIAL;
                    _rE_ACTONOTARIAL = value;
                    FixupRE_ACTONOTARIAL(previousValue);
                    OnNavigationPropertyChanged("RE_ACTONOTARIAL");
                }
            }
        }
        private RE_ACTONOTARIAL _rE_ACTONOTARIAL;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
    
    
    
    		private Int16 _sOficinaConsularId;
    	[DataMember]
        public Int16 OficinaConsularId
        {
            get
            {
    			return _sOficinaConsularId;
    		}
    		set
    		{
    			_sOficinaConsularId = value;
    		}
    	}
    	private Int16 _sDiferenciaHoraria;
    	[DataMember]
        public Int16 DiferenciaHoraria
        {
            get
            {
    			return _sDiferenciaHoraria;
    		}
    		set
    		{
    			_sDiferenciaHoraria = value;
    		}
    	}
    	private Int16 _sHorarioVerano;
    	[DataMember]
        public Int16 HorarioVerano
        {
            get
            {
    			return _sHorarioVerano;
    		}
    		set
    		{
    			_sHorarioVerano = value;
    		}
    	}
    
    
    
    
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            RE_EMPRESA = null;
            SE_USUARIO = null;
            SE_USUARIO1 = null;
            SE_USUARIO2 = null;
            RE_PERSONA = null;
            SI_PARAMETRO = null;
            RE_ACTONOTARIAL = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupRE_EMPRESA(RE_EMPRESA previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
            {
                previousValue.RE_ACTONOTARIALPARTICIPANTE.Remove(this);
            }
    
            if (RE_EMPRESA != null)
            {
                if (!RE_EMPRESA.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
                {
                    RE_EMPRESA.RE_ACTONOTARIALPARTICIPANTE.Add(this);
                }
    
                anpa_iEmpresaId = RE_EMPRESA.empr_iEmpresaId;
            }
            else if (!skipKeys)
            {
                anpa_iEmpresaId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RE_EMPRESA")
                    && (ChangeTracker.OriginalValues["RE_EMPRESA"] == RE_EMPRESA))
                {
                    ChangeTracker.OriginalValues.Remove("RE_EMPRESA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RE_EMPRESA", previousValue);
                }
                if (RE_EMPRESA != null && !RE_EMPRESA.ChangeTracker.ChangeTrackingEnabled)
                {
                    RE_EMPRESA.StartTracking();
                }
            }
        }
    
        private void FixupSE_USUARIO(SE_USUARIO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
            {
                previousValue.RE_ACTONOTARIALPARTICIPANTE.Remove(this);
            }
    
            if (SE_USUARIO != null)
            {
                if (!SE_USUARIO.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
                {
                    SE_USUARIO.RE_ACTONOTARIALPARTICIPANTE.Add(this);
                }
    
                anpa_sUsuarioCreacion = SE_USUARIO.usua_sUsuarioId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SE_USUARIO")
                    && (ChangeTracker.OriginalValues["SE_USUARIO"] == SE_USUARIO))
                {
                    ChangeTracker.OriginalValues.Remove("SE_USUARIO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SE_USUARIO", previousValue);
                }
                if (SE_USUARIO != null && !SE_USUARIO.ChangeTracker.ChangeTrackingEnabled)
                {
                    SE_USUARIO.StartTracking();
                }
            }
        }
    
        private void FixupSE_USUARIO1(SE_USUARIO previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_ACTONOTARIALPARTICIPANTE1.Contains(this))
            {
                previousValue.RE_ACTONOTARIALPARTICIPANTE1.Remove(this);
            }
    
            if (SE_USUARIO1 != null)
            {
                if (!SE_USUARIO1.RE_ACTONOTARIALPARTICIPANTE1.Contains(this))
                {
                    SE_USUARIO1.RE_ACTONOTARIALPARTICIPANTE1.Add(this);
                }
    
                anpa_sUsuarioModificacion = SE_USUARIO1.usua_sUsuarioId;
            }
            else if (!skipKeys)
            {
                anpa_sUsuarioModificacion = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SE_USUARIO1")
                    && (ChangeTracker.OriginalValues["SE_USUARIO1"] == SE_USUARIO1))
                {
                    ChangeTracker.OriginalValues.Remove("SE_USUARIO1");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SE_USUARIO1", previousValue);
                }
                if (SE_USUARIO1 != null && !SE_USUARIO1.ChangeTracker.ChangeTrackingEnabled)
                {
                    SE_USUARIO1.StartTracking();
                }
            }
        }
    
        private void FixupSE_USUARIO2(SE_USUARIO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_ACTONOTARIALPARTICIPANTE2.Contains(this))
            {
                previousValue.RE_ACTONOTARIALPARTICIPANTE2.Remove(this);
            }
    
            if (SE_USUARIO2 != null)
            {
                if (!SE_USUARIO2.RE_ACTONOTARIALPARTICIPANTE2.Contains(this))
                {
                    SE_USUARIO2.RE_ACTONOTARIALPARTICIPANTE2.Add(this);
                }
    
                anpa_sTipoParticipanteId = SE_USUARIO2.usua_sUsuarioId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SE_USUARIO2")
                    && (ChangeTracker.OriginalValues["SE_USUARIO2"] == SE_USUARIO2))
                {
                    ChangeTracker.OriginalValues.Remove("SE_USUARIO2");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SE_USUARIO2", previousValue);
                }
                if (SE_USUARIO2 != null && !SE_USUARIO2.ChangeTracker.ChangeTrackingEnabled)
                {
                    SE_USUARIO2.StartTracking();
                }
            }
        }
    
        private void FixupRE_PERSONA(RE_PERSONA previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
            {
                previousValue.RE_ACTONOTARIALPARTICIPANTE.Remove(this);
            }
    
            if (RE_PERSONA != null)
            {
                if (!RE_PERSONA.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
                {
                    RE_PERSONA.RE_ACTONOTARIALPARTICIPANTE.Add(this);
                }
    
                anpa_iPersonaId = RE_PERSONA.pers_iPersonaId;
            }
            else if (!skipKeys)
            {
                anpa_iPersonaId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RE_PERSONA")
                    && (ChangeTracker.OriginalValues["RE_PERSONA"] == RE_PERSONA))
                {
                    ChangeTracker.OriginalValues.Remove("RE_PERSONA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RE_PERSONA", previousValue);
                }
                if (RE_PERSONA != null && !RE_PERSONA.ChangeTracker.ChangeTrackingEnabled)
                {
                    RE_PERSONA.StartTracking();
                }
            }
        }
    
        private void FixupSI_PARAMETRO(SI_PARAMETRO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
            {
                previousValue.RE_ACTONOTARIALPARTICIPANTE.Remove(this);
            }
    
            if (SI_PARAMETRO != null)
            {
                if (!SI_PARAMETRO.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
                {
                    SI_PARAMETRO.RE_ACTONOTARIALPARTICIPANTE.Add(this);
                }
    
                anpa_sTipoParticipanteId = SI_PARAMETRO.para_sParametroId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SI_PARAMETRO")
                    && (ChangeTracker.OriginalValues["SI_PARAMETRO"] == SI_PARAMETRO))
                {
                    ChangeTracker.OriginalValues.Remove("SI_PARAMETRO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SI_PARAMETRO", previousValue);
                }
                if (SI_PARAMETRO != null && !SI_PARAMETRO.ChangeTracker.ChangeTrackingEnabled)
                {
                    SI_PARAMETRO.StartTracking();
                }
            }
        }
    
        private void FixupRE_ACTONOTARIAL(RE_ACTONOTARIAL previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
            {
                previousValue.RE_ACTONOTARIALPARTICIPANTE.Remove(this);
            }
    
            if (RE_ACTONOTARIAL != null)
            {
                if (!RE_ACTONOTARIAL.RE_ACTONOTARIALPARTICIPANTE.Contains(this))
                {
                    RE_ACTONOTARIAL.RE_ACTONOTARIALPARTICIPANTE.Add(this);
                }
    
                anpa_iActoNotarialId = RE_ACTONOTARIAL.acno_iActoNotarialId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RE_ACTONOTARIAL")
                    && (ChangeTracker.OriginalValues["RE_ACTONOTARIAL"] == RE_ACTONOTARIAL))
                {
                    ChangeTracker.OriginalValues.Remove("RE_ACTONOTARIAL");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RE_ACTONOTARIAL", previousValue);
                }
                if (RE_ACTONOTARIAL != null && !RE_ACTONOTARIAL.ChangeTracker.ChangeTrackingEnabled)
                {
                    RE_ACTONOTARIAL.StartTracking();
                }
            }
        }

        #endregion
    }
}
