//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SGAC.WebApp.Reportes.RSAntecedentes {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("AntecedentePenal")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class AntecedentePenal : global::System.Data.DataSet {
        
        private DTAntecedentePenalDataTable tableDTAntecedentePenal;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public AntecedentePenal() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected AntecedentePenal(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DTAntecedentePenal"] != null)) {
                    base.Tables.Add(new DTAntecedentePenalDataTable(ds.Tables["DTAntecedentePenal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DTAntecedentePenalDataTable DTAntecedentePenal {
            get {
                return this.tableDTAntecedentePenal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            AntecedentePenal cln = ((AntecedentePenal)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DTAntecedentePenal"] != null)) {
                    base.Tables.Add(new DTAntecedentePenalDataTable(ds.Tables["DTAntecedentePenal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableDTAntecedentePenal = ((DTAntecedentePenalDataTable)(base.Tables["DTAntecedentePenal"]));
            if ((initTable == true)) {
                if ((this.tableDTAntecedentePenal != null)) {
                    this.tableDTAntecedentePenal.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "AntecedentePenal";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/AntecedentePenal.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDTAntecedentePenal = new DTAntecedentePenalDataTable();
            base.Tables.Add(this.tableDTAntecedentePenal);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeDTAntecedentePenal() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            AntecedentePenal ds = new AntecedentePenal();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void DTAntecedentePenalRowChangeEventHandler(object sender, DTAntecedentePenalRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DTAntecedentePenalDataTable : global::System.Data.TypedTableBase<DTAntecedentePenalRow> {
            
            private global::System.Data.DataColumn columnanpe_iAntecedentePenalId;
            
            private global::System.Data.DataColumn columnanpe_iActuacionDetalleId;
            
            private global::System.Data.DataColumn columnanpe_vNumeroSolicitud;
            
            private global::System.Data.DataColumn columnanpe_iFuncionarioId;
            
            private global::System.Data.DataColumn columnanpe_dFechaSolicitud;
            
            private global::System.Data.DataColumn columnanpe_vNumeroOficioRpta;
            
            private global::System.Data.DataColumn columnanpe_dFechaRespuesta;
            
            private global::System.Data.DataColumn columnanpe_vObservacion;
            
            private global::System.Data.DataColumn columnpago_FMontoSolesConsulares;
            
            private global::System.Data.DataColumn columnpago_FMontoMonedaLocal;
            
            private global::System.Data.DataColumn columnvSolicitante;
            
            private global::System.Data.DataColumn columnvUsuarioFuncionario;
            
            private global::System.Data.DataColumn columniNumero;
            
            private global::System.Data.DataColumn columnvNumeroDocumento;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DTAntecedentePenalDataTable() {
                this.TableName = "DTAntecedentePenal";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal DTAntecedentePenalDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected DTAntecedentePenalDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_iAntecedentePenalIdColumn {
                get {
                    return this.columnanpe_iAntecedentePenalId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_iActuacionDetalleIdColumn {
                get {
                    return this.columnanpe_iActuacionDetalleId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_vNumeroSolicitudColumn {
                get {
                    return this.columnanpe_vNumeroSolicitud;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_iFuncionarioIdColumn {
                get {
                    return this.columnanpe_iFuncionarioId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_dFechaSolicitudColumn {
                get {
                    return this.columnanpe_dFechaSolicitud;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_vNumeroOficioRptaColumn {
                get {
                    return this.columnanpe_vNumeroOficioRpta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_dFechaRespuestaColumn {
                get {
                    return this.columnanpe_dFechaRespuesta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn anpe_vObservacionColumn {
                get {
                    return this.columnanpe_vObservacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pago_FMontoSolesConsularesColumn {
                get {
                    return this.columnpago_FMontoSolesConsulares;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pago_FMontoMonedaLocalColumn {
                get {
                    return this.columnpago_FMontoMonedaLocal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn vSolicitanteColumn {
                get {
                    return this.columnvSolicitante;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn vUsuarioFuncionarioColumn {
                get {
                    return this.columnvUsuarioFuncionario;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn iNumeroColumn {
                get {
                    return this.columniNumero;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn vNumeroDocumentoColumn {
                get {
                    return this.columnvNumeroDocumento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DTAntecedentePenalRow this[int index] {
                get {
                    return ((DTAntecedentePenalRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DTAntecedentePenalRowChangeEventHandler DTAntecedentePenalRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DTAntecedentePenalRowChangeEventHandler DTAntecedentePenalRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DTAntecedentePenalRowChangeEventHandler DTAntecedentePenalRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DTAntecedentePenalRowChangeEventHandler DTAntecedentePenalRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddDTAntecedentePenalRow(DTAntecedentePenalRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DTAntecedentePenalRow AddDTAntecedentePenalRow(string anpe_iAntecedentePenalId, string anpe_iActuacionDetalleId, string anpe_vNumeroSolicitud, string anpe_iFuncionarioId, string anpe_dFechaSolicitud, string anpe_vNumeroOficioRpta, string anpe_dFechaRespuesta, string anpe_vObservacion, string pago_FMontoSolesConsulares, string pago_FMontoMonedaLocal, string vSolicitante, string vUsuarioFuncionario, string iNumero, string vNumeroDocumento) {
                DTAntecedentePenalRow rowDTAntecedentePenalRow = ((DTAntecedentePenalRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        anpe_iAntecedentePenalId,
                        anpe_iActuacionDetalleId,
                        anpe_vNumeroSolicitud,
                        anpe_iFuncionarioId,
                        anpe_dFechaSolicitud,
                        anpe_vNumeroOficioRpta,
                        anpe_dFechaRespuesta,
                        anpe_vObservacion,
                        pago_FMontoSolesConsulares,
                        pago_FMontoMonedaLocal,
                        vSolicitante,
                        vUsuarioFuncionario,
                        iNumero,
                        vNumeroDocumento};
                rowDTAntecedentePenalRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDTAntecedentePenalRow);
                return rowDTAntecedentePenalRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                DTAntecedentePenalDataTable cln = ((DTAntecedentePenalDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DTAntecedentePenalDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnanpe_iAntecedentePenalId = base.Columns["anpe_iAntecedentePenalId"];
                this.columnanpe_iActuacionDetalleId = base.Columns["anpe_iActuacionDetalleId"];
                this.columnanpe_vNumeroSolicitud = base.Columns["anpe_vNumeroSolicitud"];
                this.columnanpe_iFuncionarioId = base.Columns["anpe_iFuncionarioId"];
                this.columnanpe_dFechaSolicitud = base.Columns["anpe_dFechaSolicitud"];
                this.columnanpe_vNumeroOficioRpta = base.Columns["anpe_vNumeroOficioRpta"];
                this.columnanpe_dFechaRespuesta = base.Columns["anpe_dFechaRespuesta"];
                this.columnanpe_vObservacion = base.Columns["anpe_vObservacion"];
                this.columnpago_FMontoSolesConsulares = base.Columns["pago_FMontoSolesConsulares"];
                this.columnpago_FMontoMonedaLocal = base.Columns["pago_FMontoMonedaLocal"];
                this.columnvSolicitante = base.Columns["vSolicitante"];
                this.columnvUsuarioFuncionario = base.Columns["vUsuarioFuncionario"];
                this.columniNumero = base.Columns["iNumero"];
                this.columnvNumeroDocumento = base.Columns["vNumeroDocumento"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnanpe_iAntecedentePenalId = new global::System.Data.DataColumn("anpe_iAntecedentePenalId", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_iAntecedentePenalId);
                this.columnanpe_iActuacionDetalleId = new global::System.Data.DataColumn("anpe_iActuacionDetalleId", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_iActuacionDetalleId);
                this.columnanpe_vNumeroSolicitud = new global::System.Data.DataColumn("anpe_vNumeroSolicitud", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_vNumeroSolicitud);
                this.columnanpe_iFuncionarioId = new global::System.Data.DataColumn("anpe_iFuncionarioId", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_iFuncionarioId);
                this.columnanpe_dFechaSolicitud = new global::System.Data.DataColumn("anpe_dFechaSolicitud", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_dFechaSolicitud);
                this.columnanpe_vNumeroOficioRpta = new global::System.Data.DataColumn("anpe_vNumeroOficioRpta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_vNumeroOficioRpta);
                this.columnanpe_dFechaRespuesta = new global::System.Data.DataColumn("anpe_dFechaRespuesta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_dFechaRespuesta);
                this.columnanpe_vObservacion = new global::System.Data.DataColumn("anpe_vObservacion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnanpe_vObservacion);
                this.columnpago_FMontoSolesConsulares = new global::System.Data.DataColumn("pago_FMontoSolesConsulares", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpago_FMontoSolesConsulares);
                this.columnpago_FMontoMonedaLocal = new global::System.Data.DataColumn("pago_FMontoMonedaLocal", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpago_FMontoMonedaLocal);
                this.columnvSolicitante = new global::System.Data.DataColumn("vSolicitante", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnvSolicitante);
                this.columnvUsuarioFuncionario = new global::System.Data.DataColumn("vUsuarioFuncionario", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnvUsuarioFuncionario);
                this.columniNumero = new global::System.Data.DataColumn("iNumero", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columniNumero);
                this.columnvNumeroDocumento = new global::System.Data.DataColumn("vNumeroDocumento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnvNumeroDocumento);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DTAntecedentePenalRow NewDTAntecedentePenalRow() {
                return ((DTAntecedentePenalRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DTAntecedentePenalRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(DTAntecedentePenalRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DTAntecedentePenalRowChanged != null)) {
                    this.DTAntecedentePenalRowChanged(this, new DTAntecedentePenalRowChangeEvent(((DTAntecedentePenalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DTAntecedentePenalRowChanging != null)) {
                    this.DTAntecedentePenalRowChanging(this, new DTAntecedentePenalRowChangeEvent(((DTAntecedentePenalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DTAntecedentePenalRowDeleted != null)) {
                    this.DTAntecedentePenalRowDeleted(this, new DTAntecedentePenalRowChangeEvent(((DTAntecedentePenalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DTAntecedentePenalRowDeleting != null)) {
                    this.DTAntecedentePenalRowDeleting(this, new DTAntecedentePenalRowChangeEvent(((DTAntecedentePenalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveDTAntecedentePenalRow(DTAntecedentePenalRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                AntecedentePenal ds = new AntecedentePenal();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DTAntecedentePenalDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class DTAntecedentePenalRow : global::System.Data.DataRow {
            
            private DTAntecedentePenalDataTable tableDTAntecedentePenal;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal DTAntecedentePenalRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDTAntecedentePenal = ((DTAntecedentePenalDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_iAntecedentePenalId {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_iAntecedentePenalIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_iAntecedentePenalId\' in table \'DTAntecedentePenal\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_iAntecedentePenalIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_iActuacionDetalleId {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_iActuacionDetalleIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_iActuacionDetalleId\' in table \'DTAntecedentePenal\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_iActuacionDetalleIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_vNumeroSolicitud {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_vNumeroSolicitudColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_vNumeroSolicitud\' in table \'DTAntecedentePenal\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_vNumeroSolicitudColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_iFuncionarioId {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_iFuncionarioIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_iFuncionarioId\' in table \'DTAntecedentePenal\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_iFuncionarioIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_dFechaSolicitud {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_dFechaSolicitudColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_dFechaSolicitud\' in table \'DTAntecedentePenal\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_dFechaSolicitudColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_vNumeroOficioRpta {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_vNumeroOficioRptaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_vNumeroOficioRpta\' in table \'DTAntecedentePenal\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_vNumeroOficioRptaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_dFechaRespuesta {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_dFechaRespuestaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_dFechaRespuesta\' in table \'DTAntecedentePenal\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_dFechaRespuestaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string anpe_vObservacion {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.anpe_vObservacionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'anpe_vObservacion\' in table \'DTAntecedentePenal\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.anpe_vObservacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pago_FMontoSolesConsulares {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.pago_FMontoSolesConsularesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pago_FMontoSolesConsulares\' in table \'DTAntecedentePenal\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.pago_FMontoSolesConsularesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pago_FMontoMonedaLocal {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.pago_FMontoMonedaLocalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pago_FMontoMonedaLocal\' in table \'DTAntecedentePenal\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.pago_FMontoMonedaLocalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string vSolicitante {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.vSolicitanteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'vSolicitante\' in table \'DTAntecedentePenal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.vSolicitanteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string vUsuarioFuncionario {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.vUsuarioFuncionarioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'vUsuarioFuncionario\' in table \'DTAntecedentePenal\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.vUsuarioFuncionarioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string iNumero {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.iNumeroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'iNumero\' in table \'DTAntecedentePenal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.iNumeroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string vNumeroDocumento {
                get {
                    try {
                        return ((string)(this[this.tableDTAntecedentePenal.vNumeroDocumentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'vNumeroDocumento\' in table \'DTAntecedentePenal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTAntecedentePenal.vNumeroDocumentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_iAntecedentePenalIdNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_iAntecedentePenalIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_iAntecedentePenalIdNull() {
                this[this.tableDTAntecedentePenal.anpe_iAntecedentePenalIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_iActuacionDetalleIdNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_iActuacionDetalleIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_iActuacionDetalleIdNull() {
                this[this.tableDTAntecedentePenal.anpe_iActuacionDetalleIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_vNumeroSolicitudNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_vNumeroSolicitudColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_vNumeroSolicitudNull() {
                this[this.tableDTAntecedentePenal.anpe_vNumeroSolicitudColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_iFuncionarioIdNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_iFuncionarioIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_iFuncionarioIdNull() {
                this[this.tableDTAntecedentePenal.anpe_iFuncionarioIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_dFechaSolicitudNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_dFechaSolicitudColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_dFechaSolicitudNull() {
                this[this.tableDTAntecedentePenal.anpe_dFechaSolicitudColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_vNumeroOficioRptaNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_vNumeroOficioRptaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_vNumeroOficioRptaNull() {
                this[this.tableDTAntecedentePenal.anpe_vNumeroOficioRptaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_dFechaRespuestaNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_dFechaRespuestaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_dFechaRespuestaNull() {
                this[this.tableDTAntecedentePenal.anpe_dFechaRespuestaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isanpe_vObservacionNull() {
                return this.IsNull(this.tableDTAntecedentePenal.anpe_vObservacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setanpe_vObservacionNull() {
                this[this.tableDTAntecedentePenal.anpe_vObservacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ispago_FMontoSolesConsularesNull() {
                return this.IsNull(this.tableDTAntecedentePenal.pago_FMontoSolesConsularesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setpago_FMontoSolesConsularesNull() {
                this[this.tableDTAntecedentePenal.pago_FMontoSolesConsularesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ispago_FMontoMonedaLocalNull() {
                return this.IsNull(this.tableDTAntecedentePenal.pago_FMontoMonedaLocalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setpago_FMontoMonedaLocalNull() {
                this[this.tableDTAntecedentePenal.pago_FMontoMonedaLocalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsvSolicitanteNull() {
                return this.IsNull(this.tableDTAntecedentePenal.vSolicitanteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetvSolicitanteNull() {
                this[this.tableDTAntecedentePenal.vSolicitanteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsvUsuarioFuncionarioNull() {
                return this.IsNull(this.tableDTAntecedentePenal.vUsuarioFuncionarioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetvUsuarioFuncionarioNull() {
                this[this.tableDTAntecedentePenal.vUsuarioFuncionarioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsiNumeroNull() {
                return this.IsNull(this.tableDTAntecedentePenal.iNumeroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetiNumeroNull() {
                this[this.tableDTAntecedentePenal.iNumeroColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsvNumeroDocumentoNull() {
                return this.IsNull(this.tableDTAntecedentePenal.vNumeroDocumentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetvNumeroDocumentoNull() {
                this[this.tableDTAntecedentePenal.vNumeroDocumentoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class DTAntecedentePenalRowChangeEvent : global::System.EventArgs {
            
            private DTAntecedentePenalRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DTAntecedentePenalRowChangeEvent(DTAntecedentePenalRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DTAntecedentePenalRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591