USE BD_CARDIP

DECLARE @FK_TABLE VARCHAR(MAX)='FK_REGISTRO_LINEA_CARNE_IDENTIDAD'
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS C 
	WHERE C.CONSTRAINT_NAME = @FK_TABLE
	AND C.TABLE_NAME = 'RL_REGISTRO_LINEA'
	AND C.CONSTRAINT_SCHEMA = 'SC_REGLINEA'
	)
BEGIN
	ALTER TABLE [SC_REGLINEA].[RL_REGISTRO_LINEA]
		DROP CONSTRAINT [FK_REGISTRO_LINEA_CARNE_IDENTIDAD];

	PRINT 'CONSTRAINT '+@FK_TABLE+' ¡¡AFECTADO!!'
END

GO



