USE [BD_CARDIP]
GO

ALTER TABLE [SC_CARDIP].[CD_CARNE_IDENTIDAD_HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_HISTORICO_CARNE_IDENTIDAD_CARNE_IDENTIDAD_ID] FOREIGN KEY([CIHI_ICARNE_IDENTIDADID])
REFERENCES [SC_CARDIP].[CD_CARNE_IDENTIDAD] ([CAID_ICARNE_IDENTIDADID])
GO

ALTER TABLE [SC_CARDIP].[CD_CARNE_IDENTIDAD_HISTORICO] CHECK CONSTRAINT [FK_HISTORICO_CARNE_IDENTIDAD_CARNE_IDENTIDAD_ID]
GO
