USE [BD_CARDIP]
GO

ALTER TABLE [SC_CARDIP].[CD_MOVIMIENTO_CARNE_IDENTIDAD]  WITH CHECK ADD  CONSTRAINT [FK_MOVIMIENTO_CARNE_IDENTIDAD_CARNE_IDENTIDAD_ID] FOREIGN KEY([MOCI_ICARNE_IDENTIDADID])
REFERENCES [SC_CARDIP].[CD_CARNE_IDENTIDAD] ([CAID_ICARNE_IDENTIDADID])
GO

ALTER TABLE [SC_CARDIP].[CD_MOVIMIENTO_CARNE_IDENTIDAD] CHECK CONSTRAINT [FK_MOVIMIENTO_CARNE_IDENTIDAD_CARNE_IDENTIDAD_ID]
GO
