USE [BD_CARDIP]
GO

ALTER TABLE [SC_REGLINEA].[RL_REGISTRO_LINEA]  WITH CHECK ADD  CONSTRAINT [FK_REGISTRO_LINEA_CARNE_IDENTIDAD] FOREIGN KEY([RELI_ICARNE_IDENTIDAD_ID])
REFERENCES [SC_CARDIP].[CD_CARNE_IDENTIDAD] ([CAID_ICARNE_IDENTIDADID])
GO

ALTER TABLE [SC_REGLINEA].[RL_REGISTRO_LINEA] CHECK CONSTRAINT [FK_REGISTRO_LINEA_CARNE_IDENTIDAD]
GO
