USE [BD_CARDIP]
GO


INSERT INTO[PS_SISTEMA].[SI_PARAMETRO]([PARA_VGRUPO],[PARA_VDESCRIPCION],[PARA_VVALOR],[PARA_VREFERENCIA],[PARA_TORDEN],[PARA_BVISIBLE],[PARA_DVIGENCIAINICIO],[PARA_DVIGENCIAFIN],[PARA_BPRECARGA],[PARA_CESTADO],[PARA_SUSUARIOCREACION],[PARA_VIPCREACION],[PARA_DFECHACREACION],[PARA_SUSUARIOMODIFICACION],[PARA_VIPMODIFICACION],[PARA_DFECHAMODIFICACION])
VALUES('ACTOMIGRATORIO-VISATIPOTEMPORAL','EQUIPO DE PRODUCCIÓN','ART',358,1,1,'1900-01-01 00:00:00.000','1900-01-01 00:00:00.000',1,'A',1,'192.168.1.246',GETDATE(),NULL,NULL,NULL)

GO

