USE [BD_CARDIP]
GO

INSERT INTO[SC_MAESTRO].[MA_CALIDAD_MIGRATORIA]([CAMI_VNUMERO_ORDEN],[CAMI_SFLAG_TITULAR_DEPENDIENTE],[CAMI_SFLAG_NIVEL_CALIDAD],[CAMI_SREFERENCIA_ID],[CAMI_VNOMBRE],[CAMI_VDEFINICION],[CAMI_CESTADO],[CAMI_SUSUARIOCREACION],[CAMI_VIPCREACION],[CAMI_DFECHACREACION],[CAMI_SUSUARIOMODIFICACION],[CAMI_VIPMODIFICACION],[CAMI_DFECHAMODIFICACION],[CAMI_GENERO])
VALUES(NULL,11209,1,358,'TÉCNICO',NULL,'A',1,'0.0.0.0',GETDATE(),NULL,NULL,NULL,2001)

GO




