
USE [BD_CARDIP]
GO
--======================================================================
--SISTEMA		:	CARDIP -administrador
--OBJETIVO		:	Adicion de campo observacion con la finalidad de grabar el motivo de la observacion del tramite de carnet	
--CREADO POR	:	VPIPA
--FECHA			:	29/06/2021
--======================================================================
IF NOT EXISTS ( SELECT name  FROM   sys.columns  WHERE  object_id = OBJECT_ID(N'[SC_CARDIP].[CD_CARNE_IDENTIDAD]')  AND name = 'CAID_VOBSERVACION' )
begin
	alter table SC_CARDIP.CD_CARNE_IDENTIDAD add CAID_VOBSERVACION varchar(250) null
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'PARA GRABAR EL MOTIVO DE LA OBSERVACION DEL TRAMITE DE CARNET' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_CARDIP', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'CD_CARNE_IDENTIDAD', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'CAID_VOBSERVACION'
end
go


--======================================================================
--SISTEMA		:	CARDIP -administrador
--OBJETIVO		:	adicion de Estado de observacion a la tabla de Estado, debido a la necesidad de  cambiar el estado a observado en el sistema Cardip 
--CREADO POR	:	VPIPA
--FECHA			:	29/06/2021	
--======================================================================
IF NOT EXISTS (SELECT ESTA_VGRUPO FROM SC_MAESTRO.MA_ESTADO WHERE ESTA_VGRUPO='CARNE IDENTIDAD - ESTADO' AND ESTA_VDESCRIPCIONCORTA='OBSERVADO') BEGIN
	INSERT INTO SC_MAESTRO.MA_ESTADO ( ESTA_VDESCRIPCIONCORTA,ESTA_VDESCRIPCIONLARGA,ESTA_VGRUPO,ESTA_CESTADO,ESTA_SUSUARIOCREACION,ESTA_VIPCREACION,ESTA_DFECHACREACION,ESTA_SUSUARIOMODIFICACION,ESTA_VIPMODIFICACION,ESTA_DFECHAMODIFICACION)
	VALUES( 'OBSERVADO','OBSERVADO','CARNE IDENTIDAD - ESTADO','A',1,'0.0.0.0',GETDATE(),NULL,NULL,NULL)
END
go



--======================================================================
--SISTEMA		:	CARDIP - REg-Linea
--OBJETIVO		:	adicion de Estado de atendido a la tabla de Estado, debido a la necesidad de  cambiar el estado a estado atendedido en el sistema Cardip en linea
--CREADO POR	:	VPIPA
--FECHA			:	29/06/2021	
--======================================================================
IF NOT EXISTS (SELECT ESTA_VDESCRIPCIONCORTA FROM SC_MAESTRO.MA_ESTADO WHERE ESTA_VGRUPO='REG LINEA - ESTADO' AND ESTA_VDESCRIPCIONCORTA='ATENDIDO') BEGIN
	INSERT INTO SC_MAESTRO.MA_ESTADO ( ESTA_VDESCRIPCIONCORTA,ESTA_VDESCRIPCIONLARGA,ESTA_VGRUPO,ESTA_CESTADO,ESTA_SUSUARIOCREACION,ESTA_VIPCREACION,ESTA_DFECHACREACION,ESTA_SUSUARIOMODIFICACION,ESTA_VIPMODIFICACION,ESTA_DFECHAMODIFICACION)
	VALUES( 'ATENDIDO','ATENDIDO','REG LINEA - ESTADO','A',1,'0.0.0.0',GETDATE(),NULL,NULL,NULL)
END
go
IF NOT EXISTS (SELECT ESTA_VDESCRIPCIONCORTA FROM SC_MAESTRO.MA_ESTADO WHERE ESTA_VGRUPO='REG LINEA - ESTADO' AND ESTA_VDESCRIPCIONCORTA='SUBSANADO') BEGIN
	INSERT INTO SC_MAESTRO.MA_ESTADO ( ESTA_VDESCRIPCIONCORTA,ESTA_VDESCRIPCIONLARGA,ESTA_VGRUPO,ESTA_CESTADO,ESTA_SUSUARIOCREACION,ESTA_VIPCREACION,ESTA_DFECHACREACION,ESTA_SUSUARIOMODIFICACION,ESTA_VIPMODIFICACION,ESTA_DFECHAMODIFICACION)
	VALUES( 'SUBSANADO','SUBSANADO','REG LINEA - ESTADO','A',1,'0.0.0.0',GETDATE(),NULL,NULL,NULL)
END
go


--======================================================================
--SISTEMA		:	CARDIP - REg-Linea
--OBJETIVO		:	Creacion de tabla CD_MENSAJE_ESTADO con la finalidad de configurar el mensaje por Estado. 
--					ejemplo para el estado de Oservado se configura un mensaje, esto se enviará automaticamente 
--					desde el sistema de cardip al observar la solicitud de carnet
--CREADO POR	:	VPIPA
--FECHA			:	29/06/2021
--Tabla			: CD_MENSAJE_ESTADO
--Columnas		:
--				MEES_SESTADOID : id del estado referenciado al tabla maestra  SC_MAESTRO.MA_ESTADO
--				MEES_VMENSAJE : CAMPO PARA GRABAR EL TEXTO DEL MENSAJE
--				MEES_CESTADO  : campo para habilitar o inabilitar el registro
--======================================================================
IF NOT EXISTS (SELECT XTYPE FROM SYSOBJECTS WHERE NAME='CD_MENSAJE_ESTADO' AND XTYPE='U')
BEGIN
CREATE  TABLE SC_CARDIP.CD_MENSAJE_ESTADO(
	MEES_SESTADOID   SMALLINT ,
	MEES_VMENSAJE VARCHAR(250),
	MEES_CESTADO CHAR(1)
	CONSTRAINT [pk_MEES_SESTADOID] PRIMARY KEY CLUSTERED (	MEES_SESTADOID),
	CONSTRAINT [FK_SE_CD_MENSAJE_ESTADO] FOREIGN KEY(MEES_SESTADOID) REFERENCES SC_MAESTRO.MA_ESTADO (ESTA_SESTADOID)
)
END

go

IF NOT EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE     P.MAJOR_ID = OBJECT_ID('SC_CARDIP.CD_MENSAJE_ESTADO')) BEGIN
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'ID DEL ESTADO REFERENCIADO AL TABLA MAESTRA  SC_MAESTRO.MA_ESTADO' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_CARDIP', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'CD_MENSAJE_ESTADO', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'MEES_SESTADOID'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'CAMPO PARA GRABAR EL TEXTO DEL MENSAJE' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_CARDIP', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'CD_MENSAJE_ESTADO', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'MEES_VMENSAJE'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'campo para habilitar o inabilitar el registro' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_CARDIP', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'CD_MENSAJE_ESTADO', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'MEES_CESTADO'

END

