USE [BD_CARDIP]
GO

	ALTER PROCEDURE [PN_REGISTRO].[USP_RE_PERSONA_IDENTIFICACION_ADICIONAR]
	--================================================================================
	--SISTEMA			: MÓDULO DE CARNET PARA DIPLOMÁTICOS
	--OBJETIVO			: OBTIENE EL REGISTRO DE LA CABECERA Y EL DETALLE PARA GENERAR LA ORDEN DE PAGO
	--CREADO			: MANUEL NUNJA
	--FECHA     		: 23/11/2014 18:47:27
	--PARAMETROS        :	@P_ID_SOLICITUD			IDENTIFICADOR DE LA TABLA
	--EJECUTAR          : [SC_CARDIP].[USP_CD_GENERALES_MRE]
	--MODIFICACIONES
	--AUTOR                       FECHA      N° REQ.      MOTIVO
	--================================================================================
   -- MODIFICADO POR: JONATAN SILVA CACHAY
   -- FECHA DE MODIFICACIÒN: 21/06/2021
   -- MOTIVO: SE ACTUALIZA EL CAMPO PEID_BACTIVOENRUNE PARA QUE EXISTA SOLO 1
   --================================================================================
   -- MODIFICADO POR: VPIPA
   -- FECHA DE MODIFICACIÒN: 29/06/2021
   -- MOTIVO: SE ACTUALIZA EL CAMPO PEID_BACTIVOENRUNE PARA QUE el ultimo  1 activo
   --================================================================================ 
	@P_PERSONA_ID				BIGINT,
	@P_DOCUMENTO_TIPO_ID		SMALLINT,
	@P_DOCUMENTO_NUMERO			VARCHAR(20),
	@P_USUARIO_CREACION			SMALLINT,
	@P_IP_CREACION				VARCHAR(50)

	AS
	BEGIN
		BEGIN TRY
         DECLARE @PEID_BACTIVOENRUNE BIT = 1
         DECLARE @PEID_BINACTIVOENRUNE BIT = 0

			/*=========los anteriores registros se pone a inactivo, mientras el nuevo activo*/
		 UPDATE [PN_REGISTRO].[RE_PERSONAIDENTIFICACION]
         SET PEID_BACTIVOENRUNE =@PEID_BINACTIVOENRUNE
         WHere PEID_IPERSONAID = @P_PERSONA_ID

				INSERT INTO PN_REGISTRO.RE_PERSONAIDENTIFICACION(PEID_IPERSONAID,PEID_SDOCUMENTOTIPOID,PEID_VDOCUMENTONUMERO,PEID_SUSUARIOCREACION,PEID_VIPCREACION,PEID_DFECHACREACION,PEID_BACTIVOENRUNE)
				VALUES(@P_PERSONA_ID,@P_DOCUMENTO_TIPO_ID,@P_DOCUMENTO_NUMERO,@P_USUARIO_CREACION,@P_IP_CREACION,GETDATE(), @PEID_BACTIVOENRUNE)
		END TRY
		BEGIN CATCH
			SELECT ERROR_MESSAGE() AS ErrorMessage;
		END CATCH
		RETURN @@IDENTITY
	END


