USE [BD_CARDIP]
GO

--======================================================================
--SISTEMA		:	CARDIP - Cardip REG-Linea
--OBJETIVO		:	ADICION DE CAMPOS  PARA GRABAR LOS DATOS OBTENIDOS DESDE EL WEB SERVICE DE SAM REFERENTE A LA CALIDAD MIGRATORIO
--CREADO POR	:	VPIPA
--FECHA			:	30/06/2021
--columnas		:
--				[RELI_VTIPO_VISA]: tipo de Visa
--				[RELI_VVISA] Visa,
--				[RELI_VTITULARIDAD_FAMILIAR] : Titularida Familiar
--				[RELI_STIEMPO_PERMANENCIA]: tiempo de permanencia
--======================================================================
IF NOT EXISTS (SELECT NAME  FROM   SYS.COLUMNS   WHERE  OBJECT_ID = OBJECT_ID(N'[SC_REGLINEA].[RL_REGISTRO_LINEA]')    AND NAME = 'RELI_VTIPO_VISA')
BEGIN
	ALTER TABLE [SC_REGLINEA].[RL_REGISTRO_LINEA] ADD
		[RELI_VTIPO_VISA] [VARCHAR](2) NULL,
		[RELI_VVISA] [VARCHAR](5) NULL,
		[RELI_VTITULARIDAD_FAMILIAR] [VARCHAR](2) NULL,
		[RELI_STIEMPO_PERMANENCIA] [SMALLINT] NULL

	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'TIPO DE VISA' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'RELI_VTIPO_VISA'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'CAMPO PARA GRABAR la VISA' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'RELI_VVISA'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'Titularida Familiar' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'RELI_VTITULARIDAD_FAMILIAR'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'tiempo de permanencia' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'RELI_STIEMPO_PERMANENCIA'
END

