use BD_CARDIP
go
--======================================================================
--SISTEMA		:	CARDIP - Cardip REG-Linea
--OBJETIVO		:	creacion de tabla SC_REGLINEA.RE_LOG_ERRORES para almacenar el log de errores en el sistema de CARDIP_REG_LINEA
--CREADO POR	:	VPIPA
--FECHA			:	30/06/2021
--columnas		:
--	[LOER_ILOGERRORID]:	ID DEL REGISTRO,
--	[LOER_VNOMFORMULARIO] : NOMBRE DE FORMULARIO EN DONDE OCURRI” EL ERROR
--	[LOER_VERROR] : ERROR
--	[LOER_VDETALLEERROR] : DETALLE DEL ERROR
--	[LOER_VMETODO] : METODO EN LA APLICAION
--	[LOER_SUSUARIOCREACION] : USUARIO CREACION
--	[LOER_VIPCREACION] :IP DESDE DONDE SE EJECUTA LA APLICACION
--	[LOER_DFECHACREACION] : FECHA DE CREACION

--======================================================================
IF NOT EXISTS (SELECT XTYPE FROM SYSOBJECTS WHERE NAME='RE_LOG_ERRORES' AND XTYPE='U')
BEGIN
CREATE TABLE SC_REGLINEA.RE_LOG_ERRORES(
	[LOER_ILOGERRORID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOER_VNOMFORMULARIO] [varchar](100) NULL,
	[LOER_VERROR] [varchar](500) NULL,
	[LOER_VDETALLEERROR] [varchar](1000) NULL,
	[LOER_VMETODO] [varchar](100) NULL,
	[LOER_SUSUARIOCREACION] [smallint] NULL,
	[LOER_VIPCREACION] [varchar](20) NULL,
	[LOER_DFECHACREACION] [datetime] NULL,
 CONSTRAINT [PK_RE_LOG_ERRORES_PSC] PRIMARY KEY CLUSTERED 
(
	[LOER_ILOGERRORID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
end
GO

IF NOT EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE     P.MAJOR_ID = OBJECT_ID('SC_REGLINEA.RE_LOG_ERRORES')) BEGIN
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'ID DEL REGISTRO' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_ILOGERRORID'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'NOMBRE DE FORMULARIO EN DONDE OCURRI” EL ERROR' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_VNOMFORMULARIO'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'DESCRIPCION CORTA DEL ERROR' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_VERROR'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'DETALLE DEL ERROR' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_VDETALLEERROR'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'METODO EN LA APLICAION' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_VMETODO'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'USUARIO CREACION' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_SUSUARIOCREACION'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'IP DESDE DONDE SE EJECUTA LA APLICACION' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_VIPCREACION'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'FECHA DE CREACION' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RE_LOG_ERRORES', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'LOER_DFECHACREACION'
	
END

--======================================================================
--SISTEMA		:	CARDIP - Cardip REG-Linea
--OBJETIVO		:	creaci”n de tabla SC_REGLINEA.RL_DETALLE_REGISTRO_LINEA PARA ALMACENAR LA TRAZABILIDAD DE ESTADOS EN EL SISTEMA DE CARDIP EN LINEA 
--CREADO POR	:	VPIPA
--FECHA			:	30/06/2021
--columnas		:
--	DERE_SREG_LINEA_ID : ID REFERENCIA DEL LA TABLA DE [SC_REGLINEA].[RL_REGISTRO_LINEA]
--	DERE_SCODIGO : ID DEL REGISTRO
--	DERE_SESTADO_ID : ID DEL ESTADO REFERENCIADO A LA TABLA MAESTRA [SC_MAESTRO].[MA_ESTADO]
--	DERE_VOBSERVACION : DESCRIPCION DE OBSERVACION
--	DERE_FECHACREACION : FECHA DEL REGISTRO
--======================================================================
IF NOT EXISTS (SELECT XTYPE FROM SYSOBJECTS WHERE NAME='RL_DETALLE_REGISTRO_LINEA' AND XTYPE='U')
BEGIN
CREATE  TABLE SC_REGLINEA.RL_DETALLE_REGISTRO_LINEA(
	DERE_SREG_LINEA_ID INT,
	DERE_SCODIGO INT,
	DERE_SESTADO_ID SMALLINT,
	DERE_VOBSERVACION VARCHAR(250),
	DERE_FECHACREACION DATETIME,
	CONSTRAINT [PK_DETALLE_REGISTRO_LINEA] PRIMARY KEY(DERE_SREG_LINEA_ID,DERE_SCODIGO),
	CONSTRAINT [FK_DETALLE_REGISTRO_LINEA] FOREIGN KEY(DERE_SREG_LINEA_ID) REFERENCES  [SC_REGLINEA].[RL_REGISTRO_LINEA] (RELI_SREG_LINEA_ID),
	CONSTRAINT [FK_DETALLE_REGISTRO_LINEA_ESTADO] FOREIGN KEY(DERE_SESTADO_ID) REFERENCES [SC_MAESTRO].[MA_ESTADO] ([ESTA_SESTADOID])
)
END
IF NOT EXISTS(SELECT 1 FROM SYS.EXTENDED_PROPERTIES P WHERE     P.MAJOR_ID = OBJECT_ID('SC_REGLINEA.RL_DETALLE_REGISTRO_LINEA')) BEGIN
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'ID DEL REGISTRO' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_DETALLE_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'DERE_SREG_LINEA_ID'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'ID DEL REGISTRO' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_DETALLE_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'DERE_SCODIGO'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'ID DEL REGISTRO' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_DETALLE_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'DERE_SESTADO_ID'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'ID DEL REGISTRO' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_DETALLE_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'DERE_VOBSERVACION'
	EXEC SYS.SP_ADDEXTENDEDPROPERTY @NAME=N'MS_DESCRIPTION', @VALUE=N'ID DEL REGISTRO' , @LEVEL0TYPE=N'SCHEMA',@LEVEL0NAME=N'SC_REGLINEA', @LEVEL1TYPE=N'TABLE',@LEVEL1NAME=N'RL_DETALLE_REGISTRO_LINEA', @LEVEL2TYPE=N'COLUMN',@LEVEL2NAME=N'DERE_FECHACREACION'
	
END
