GO
use BD_CARDIP
GO

GRANT SELECT ON SC_REGLINEA.RE_LOG_ERRORES(LOER_ILOGERRORID,LOER_VNOMFORMULARIO,LOER_VERROR,LOER_VDETALLEERROR,LOER_VMETODO,LOER_SUSUARIOCREACION,LOER_VIPCREACION,LOER_DFECHACREACION) TO  AU_CARDIP,AU_REGLINEA; 
GO
GRANT SELECT ON SC_CARDIP.CD_CARNE_IDENTIDAD(CAID_DFECHACREACION,CAID_ICARNE_IDENTIDADID, CAID_SESTADOID, CAID_SREGISTRO_PREVIO) TO AU_CARDIP;
GO
GRANT EXECUTE ON OBJECT::[SC_REGLINEA].[SC_LOG_ERRORES_REGISTRAR_LOG]  TO AU_CARDIP,AU_REGLINEA
GO
GRANT EXECUTE ON OBJECT::SC_REGLINEA.USP_CD_CONSULTA_TRAZABILIDAD TO AU_CARDIP,AU_REGLINEA
go
GRANT EXECUTE ON OBJECT::[SC_REGLINEA].[USP_RL_REGISTRO_LINEA_ACTUALIZAR_DETALLEESTADO_ENVIADO] TO AU_CARDIP,AU_REGLINEA
go
GRANT EXECUTE ON OBJECT::[SC_REGLINEA].[USP_CD_CONSULTA_TRAZABILIDAD] TO AU_CARDIP,AU_REGLINEA
go
GRANT EXECUTE ON OBJECT::[SC_REGLINEA].[USP_RL_REGISTRO_LINEA_ACTUALIZAR_DETALLEESTADO_ENVIADO] TO AU_CARDIP,AU_REGLINEA
GO
GRANT SELECT ON SC_REGLINEA.RL_DETALLE_REGISTRO_LINEA(DERE_SREG_LINEA_ID, DERE_SCODIGO,DERE_SESTADO_ID, DERE_VOBSERVACION,DERE_FECHACREACION) TO AU_CARDIP,AU_REGLINEA; 


