	
	USE BD_CARDIP

	DECLARE
	@V_IPERSONAID			BIGINT,
	@V_ID					BIGINT


	BEGIN
		UPDATE PN_REGISTRO.RE_PERSONAIDENTIFICACION
		SET PEID_BACTIVOENRUNE = 1,
      PEID_SUSUARIOMODIFICACION = 1,
      PEID_VIPMODIFICACION = '1.1.1.1',
      PEID_DFECHAMODIFICACION = getdate()
		WHERE PEID_BACTIVOENRUNE IS NULL

		DECLARE R_TOP CURSOR FOR
		SELECT PEID_IPERSONAID
		FROM PN_REGISTRO.RE_PERSONAIDENTIFICACION
		GROUP BY PEID_IPERSONAID
		HAVING COUNT(PEID_IPERSONAIDENTIFICACIONID) > 1

		OPEN R_TOP FETCH NEXT FROM R_TOP INTO  @V_IPERSONAID
		WHILE @@FETCH_STATUS = 0
			BEGIN
				
				UPDATE PN_REGISTRO.RE_PERSONAIDENTIFICACION
				SET PEID_BACTIVOENRUNE = 0,
            PEID_SUSUARIOMODIFICACION = 1,
            PEID_VIPMODIFICACION = '1.1.1.1',
            PEID_DFECHAMODIFICACION =  getdate()
				WHERE PEID_IPERSONAID = @V_IPERSONAID

				SELECT TOP 1 @V_ID = PEID_IPERSONAIDENTIFICACIONID
				FROM PN_REGISTRO.RE_PERSONAIDENTIFICACION
				WHERE PEID_IPERSONAID = @V_IPERSONAID
				ORDER BY PEID_DFECHACREACION DESC

				UPDATE PN_REGISTRO.RE_PERSONAIDENTIFICACION
				SET PEID_BACTIVOENRUNE = 1,
            PEID_SUSUARIOMODIFICACION = 1,
            PEID_VIPMODIFICACION = '1.1.1.1',
            PEID_DFECHAMODIFICACION =  getdate()
				WHERE PEID_IPERSONAIDENTIFICACIONID = @V_ID

			FETCH NEXT FROM R_TOP INTO @V_IPERSONAID
			END

		CLOSE R_TOP
		DEALLOCATE R_TOP
	END