USE BD_CARDIP

DECLARE @FK_TABLE VARCHAR(MAX)='FK_ACTA_CONFORMIDAD_DETALLE_CARNE_IDENTIDAD'
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS C 
	WHERE C.CONSTRAINT_NAME = @FK_TABLE
	AND C.TABLE_NAME = 'CD_ACTA_CONFORMIDAD_DETALLE'
	AND C.CONSTRAINT_SCHEMA = 'SC_CARDIP'
	)
BEGIN
	ALTER TABLE [SC_CARDIP].[CD_ACTA_CONFORMIDAD_DETALLE]
		DROP CONSTRAINT [FK_ACTA_CONFORMIDAD_DETALLE_CARNE_IDENTIDAD];

	PRINT 'CONSTRAINT '+@FK_TABLE+' ¡¡AFECTADO!!'
END

GO



