USE BD_CARDIP

DECLARE @PK_TABLE VARCHAR(MAX)='PK_CARNE_IDENTIDAD'
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS C 
	WHERE C.CONSTRAINT_NAME = @PK_TABLE
	AND C.TABLE_NAME = 'CD_CARNE_IDENTIDAD'
	AND C.CONSTRAINT_SCHEMA = 'SC_CARDIP'
	)
BEGIN
	ALTER TABLE [SC_CARDIP].[CD_CARNE_IDENTIDAD]
		DROP CONSTRAINT [PK_CARNE_IDENTIDAD];
		
	PRINT 'CONSTRAINT '+@PK_TABLE+' ¡¡AFECTADO!!'
END

GO



