USE BD_CARDIP

DECLARE @COLUM VARCHAR(MAX)='CAIS_SCARNE_IDENTIDAD_ID'
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS AS C
	WHERE C.TABLE_SCHEMA = 'SC_CARDIP'
	AND C.TABLE_NAME = 'CD_CARNE_IDENTIDAD_SOLICITUD'
    AND C.COLUMN_NAME = @COLUM
	)
BEGIN
	ALTER TABLE [SC_CARDIP].[CD_CARNE_IDENTIDAD_SOLICITUD]
		ALTER COLUMN [CAIS_SCARNE_IDENTIDAD_ID] SMALLINT;
	
	PRINT 'CAMPO '+@COLUM+' ¡¡AFECTADA!!'
END

GO



