USE [BD_CARDIP]
GO


	UPDATE PS_SISTEMA.SI_PARAMETRO
	SET SI_PARAMETRO.PARA_CESTADO = 'E'
	WHERE SI_PARAMETRO.PARA_VDESCRIPCION = 'TÉCNICO' AND 
	SI_PARAMETRO.PARA_VREFERENCIA=358 AND 
	SI_PARAMETRO.PARA_CESTADO = 'A'

GO