USE [BD_CARDIP]
GO

	DECLARE @CAMI_SFLAG_TITULAR_DEPENDIENTE SMALLINT
	DECLARE @CAMI_SREFERENCIA_ID SMALLINT
	DECLARE @PARA_SPARAMETROID INT

	SELECT @CAMI_SFLAG_TITULAR_DEPENDIENTE = PARA_SPARAMETROID FROM [PS_SISTEMA].[SI_PARAMETRO] WITH(NOLOCK) 
												WHERE PARA_VGRUPO = 'CALIDAD MIG - TITULAR DEPENDIENTE'
												AND PARA_VDESCRIPCION = 'TITULAR'
												AND PARA_CESTADO = 'A'
	
	SELECT @CAMI_SREFERENCIA_ID = CAMI_SCALIDAD_MIGRATORIAID FROM [SC_MAESTRO].[MA_CALIDAD_MIGRATORIA] WITH(NOLOCK) 
									WHERE CAMI_VNOMBRE = 'PRODUCCIÓN ARTÍSTICA'
									AND CAMI_CESTADO = 'A'

	SELECT @PARA_SPARAMETROID = PARA_SPARAMETROID FROM [PS_SISTEMA].[SI_PARAMETRO] WITH(NOLOCK) 
									WHERE PARA_VGRUPO = 'PERSONA-GÉNERO' AND PARA_VDESCRIPCION = 'MASCULINO' 
									AND PARA_CESTADO = 'A'

	UPDATE SC_MAESTRO.MA_CALIDAD_MIGRATORIA	
	SET MA_CALIDAD_MIGRATORIA.CAMI_CESTADO = 'E'
	WHERE MA_CALIDAD_MIGRATORIA.CAMI_VNOMBRE = 'EQUIPO DE PRODUCCIÓN' AND 
	MA_CALIDAD_MIGRATORIA.CAMI_SREFERENCIA_ID = @CAMI_SREFERENCIA_ID AND
	MA_CALIDAD_MIGRATORIA.CAMI_SFLAG_TITULAR_DEPENDIENTE=@CAMI_SFLAG_TITULAR_DEPENDIENTE AND 
	MA_CALIDAD_MIGRATORIA.CAMI_CESTADO = 'A' AND
	MA_CALIDAD_MIGRATORIA.CAMI_GENERO = @PARA_SPARAMETROID


GO